# Generated by Django 4.1 on 2022-09-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('nacimiento', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
                ('nacionalidad', models.CharField(max_length=30)),
                ('participo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Peliculas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=60)),
                ('estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('genero', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=60)),
                ('temporadas', models.IntegerField()),
                ('episodios', models.IntegerField()),
                ('emision', models.DateField()),
                ('continuidad', models.CharField(max_length=10)),
            ],
        ),
    ]
