# Generated by Django 4.1 on 2022-10-10 01:07

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0002_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='peliculas',
            name='resenia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
