# Generated by Django 4.1 on 2022-10-11 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0005_series_resenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peliculas',
            name='resenia',
        ),
        migrations.RemoveField(
            model_name='series',
            name='resenia',
        ),
        migrations.AddField(
            model_name='actores',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='peliculas',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='series',
            name='fecha_ingreso',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
