# Generated by Django 4.1 on 2022-10-12 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppDjango', '0007_actores_imagen_peliculas_imagen_peliculas_resenia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actores',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='actores',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='peliculas',
            name='resenia',
        ),
        migrations.RemoveField(
            model_name='series',
            name='fecha_ingreso',
        ),
        migrations.RemoveField(
            model_name='series',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='series',
            name='resenia',
        ),
    ]
